#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format.';
    false;
)

# Check lint
npm run lint ||
(
    echo 'Eslint check failed. Check the error above and fix it.';
    false;
)

# If everything passes... Now we can commit
echo '✅ Everything looks perfect.'
