#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Checking lint before commit'

# Check lint
npm run lint ||
(
    echo 'Eslint check failed. Check the error above and fix it.';
    false;
)

# If everything passes... Now we can commit
echo '✅ Everything looks perfect.'

# yarn lint-staged
# lint-stage isn't working with yarn will be fixing soon